### ISSUE TITLE
Not working for a comic in Manga Fixed Format

### ISSUE THREAD

**Issue by renke** [Cortys/comixology-backup#46]
Hi @Cortys 

The alert message is
```
Sorry. The Scan failed.
Maybe you should try again.
```

Apparently I can't switch into single page view in this particular comic. Maybe this is causing the error? 

My chrome version is `Version 47.0.2526.8 dev (64-bit)`. I loaded the extension as unpacked extension. Is any more information I can provide to you? Also, if you can give me some hints how to track down the problem I would gladly try to fix it myself.

**Comment by Cortys** [comment]
Hi! This actually is the expected behavior.

You have to use a comic that offers single page as well as dual page view for the initial scan (because the scanner has to gather information about the various different views, which is not possible in the constrained fixed format view).

After that you should be able to scan Fixed Format comics as well though. Hope this helps.

**Comment by renke** [comment]
Ah, so it was a bad comic to start with. Thanks for the quick response, works like a charm now!
