### ISSUE TITLE
Line down 2-page spread

### ISSUE THREAD

**Issue by stevenmh** [Cortys/comixology-backup#54]
Just ran across this today and it installed fine.  In the process of backup up my Disney/Marvel Star Wars library.  It's working fine, except that I've noticed that on 2-page spreads there's a line down the middle as if it's two separate pages.  When I view in the Comixology Reader on PC or in the Comixology app on my tablet, it's an unbroken image.  Is there a setting that I need to change to avoid this, or is this just how it is?  Not complaining at all... what I have now is better than what I had before.  After collecting 4500 comics and running into space issues, I went digital a year ago, but have been bothered by the idea that my library could disappear on a publisher's whim.

Thanks very much!

**Comment by Cortys** [comment]
If there is no line visible in the web reader, there should not be one in the backup. Could you try zooming into a spreaded page in the web reader and see if there truly is no line?

If that is the case, please send me the name of one of the comics where you see this issue. I'll see what I can do about it then. Thanks!

**Comment by stevenmh** [comment]
False alarm... ComicRack for Windows is imposing the line even though it correctly recognizes the image as a single page.  I downloaded Free CBZ Reader and the 2-page spreads correctly show as unbroken images.  Sorry for the confusion, but I'm glad I thought to try another reader before you dug any deeper into it.

While I have you, and since I'm new at this, what is the history of this software?  While researching this today, it looks like there was another program that was on GitHub a couple years ago but they took it down.  I almost mistook this for the same software and didn't click the link.  Are you at the same risk of Comixology or a publisher running across this and requesting that it be removed?  Have you had to do an ongoing dance with Comixology changing DRM and then having to update the backup extension?  I hope you're able to support this for a long time.  I'd be willing to pay for it or make a donation.  There hasn't been a month that's gone by that I haven't wondered whether I'm making a mistake and should go back to hard copies.  This software is eliminating that doubt and that's worth something.

**Comment by Cortys** [comment]
Hi! Glad you could solve your problem that quickly. 

The history of this project is indeed quite twisted. 

The original code base of this is indeed the old extension you found, which itself succeeded a even more basic backup script dating back to 2012 or so. That code was maintained by "sperglord-enterprises".

After cmxlgy switched to the HTML 5 reader in 2014 the old extension stopped working and the creator did not have the time to further maintain it. So I jumped in and started working as a collaborator on the original repo adding support for the new reader. 

Cmxlgy took note of this and since the extension was popular among pirates, they started changing the reader to prevent backups, which we in turn circumvented (a relic of this is the setup wizard). In the end they simply shut down the repo because they recognized it was a useless endeavor. 

After some back and forth with GitHub I reuploaded a new version of the code, which started adding watermarks to the backups, making the extension less interesting for pirates and in turn less important for comixology. If you are really interested in the details, you can read them [here](https://github.com/Cortys/cmxlgyTalkingThread/issues/1).

A bit after that I released version 2.0, which was close to a complete rewrite of the extension. 

Since then I maintain the project without further interruptions and I intend to do so for the foreseeable future. However in the past I already got help from other great open source contributors as well, so I'm sure that the project is not solely dependent on my contributions to it. 

Hope that clears things up for you!
